apiVersion: v1
kind: Service
metadata:
  name: web2-service
spec:
  type: NodePort
  selector:
    app: web2-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30091